#!/bin/bash
# Commit user personalization and sync to Freestyle via GitHub

USER_ID=$1
if [ -z "$USER_ID" ]; then
    echo "Usage: ./commit_to_freestyle.sh <user_id>"
    exit 1
fi

BRANCH_NAME="user-${USER_ID}-personalized"

echo "🔄 Committing personalization for user: $USER_ID"
echo "🚀 This will sync to Freestyle via GitHub"

# Create/switch to user branch
git checkout -b "$BRANCH_NAME" 2>/dev/null || git checkout "$BRANCH_NAME"

# Add changes
git add services/personalization_service.py
git add src/ 2>/dev/null || true

# Commit with timestamp
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
git commit -m "Personalization for $USER_ID - $TIMESTAMP

Generated by PersonalizationService with Claude + Morph
- User behavior analysis with Claude
- Code generation with Morph
- Synced to Freestyle Git via GitHub App (ID: 1756397)
- Freestyle Identity: 49f6aada-0aa8-40c6-a564-48a314e3c14b"

echo "✅ Committed to branch: $BRANCH_NAME"

# Push to GitHub (which syncs to Freestyle)
if git remote get-url origin >/dev/null 2>&1; then
    echo "🔄 Pushing to GitHub (syncs to Freestyle)..."
    git push origin "$BRANCH_NAME"
    echo "🎉 Pushed to GitHub! Freestyle will sync automatically."
else
    echo "⚠️  No GitHub remote configured"
    echo "   Add one to enable Freestyle sync"
fi

# Switch back to main
git checkout main

echo "🎉 User personalization versioned and synced to Freestyle!"
